### ISSUE TITLE
Converting NC evacuation orders to table format

### ISSUE THREAD

**Issue by todrobbins** [hurricane-response/florence_website#12]
I'm working through `north_carolina.md` and here's a preview:

<img width="873" alt="screen shot 2018-09-12 at 10 28 25 pm" src="https://user-images.githubusercontent.com/158590/45467173-7877a480-b6db-11e8-99ae-011976c7e973.png">

What do you all think of reformatting the info like this? I'll submit a patch if it seems like a good idea.

**Comment by miklb** [comment]
I like it. Thank you
