### ISSUE TITLE
Header Nav Plan

### ISSUE THREAD

**Issue by miklb** [hurricane-response/florence_website#26]
Better IA is needed to organize critical links for the header nav, what can go in a hamburger menu on mobile (different mobile nav approach?)

**Comment by rdev0rigin** [comment]
Would a `_include/unified-header.html` be a good starting place for this? 

Maybe including the primary links in the `_config.yml` would be a good place to register pages for mobile and non-mobile?

**Comment by miklb** [comment]
It certainly needs work, I wasn't sure what direction to go as we are discussing what kind of content in the future to have.

**Comment by miklb** [comment]
Thinking about it more, using `_config.yml` for navigation would also help solve #34
