### ISSUE TITLE
Integrating the data in the florence API with CEDR

### ISSUE THREAD

**Issue by skorasaurus** [hurricane-response/florence_website#31]
CEDR provided us an additional listing of shelters; 
[dedupedlist.csv.zip](https://github.com/hurricane-response/florence_website/files/2386160/dedupedlist.csv.zip)

2 Main things to do with this: 

A]
- integrate this into florence data at https://hurricane-florence-api.herokuapp.com/shelters/
which is later pulled in at http://florenceresponse.org

Data issues:
- Add Lat/lon for several missing values; 
- Add zip for several missing columsn
- rename columns (see more below) to match the https://github.com/hurricane-response/florence-api schema:  

@Jana Pawlak (CEDR) is hoping that the florence website will be able to sync or maintain data 
with "We’ll feed you any new shelters we find especially as we shift focus to new states, and you’ll let us know as their status changes" 

Additional Workflow issues:
- Determine whether CEDR will update a shelter's status (full, etc) at https://hurricane-florence-api.herokuapp.com/  If not; how to reconcile their updates with ours. 

- Column names differ in several instances between CEDR and the florence API (eg: long vs. longitude): 

- Data is formatted slightly differently. Example: in the pets column; we use values of yes and unknown to represent whether a place is pet friendly; In human_animal_animal_friendly of CEDR's sheet, CEDR uses 'pet friendly' and 'no pets' and also additional values that captures nuances and details not included in the Florance. 

We'll need to figure out how to transform the columns to and data to match each other schemas here: 

there's a couple options here: duplicating columns with 1 column with CEDR's preference and another with the florence API - that's duplicating data and can lead to issue when you don't know which column is correct if when someone only updates one column:

or 
using a script on our end to rename the columns from one to another and format its contents. 
[agate](https://github.com/wireservice/agate) and [csvkit](https://github.com/wireservice/csvkit) are two possible tools to use but by no means the only ones to use. 
This could even be done in an excel macro possibly?

**Comment by Ednas** [comment]
Most of the data has been imported. If someone wants to finish, rows 225 - 275 are still left to be finished.

**Comment by Ednas** [comment]
Done with adding the information to the API.
