### ISSUE TITLE
move the Contact US(Website comments) out of do you need help section

### ISSUE THREAD

**Issue by ChrisTheDBA** [hurricane-response/florence_website#34]
Under the heading “Do You Need Help?,” the first link is Contact. That context would make me think help is being offered with hurricane-related issues. However, it is not for help for hurricane victims at all, it is for submitting website comments. I'd suggest making the heading Contact Us about The Website, and moving OUT of the Do You Need Help section. 

From emailed commnets

**Comment by miklb** [comment]
Agreed. Those links are generated dynamically from all Jekyll pages with the `yaml` front matter that uses the `default` page template. We need either front matter to order the nav, or a different sort.

**Comment by rdev0rigin** [comment]
In [PR#37](https://github.com/hurricane-response/florence_website/pull/37) I made use of Jekyll's `_data/` folder that we can organize lists of links. I thought it a little better than using `_config.yml` separating concerns. 

As for choice terms, I could see too that using the word **Help** in this scope would lead to confusion. I think *Help* should be reserved for the user that needs emergency services, maybe we could reword the other context's of *help* to something like `volunteer` or `contribute`?

**Comment by miklb** [comment]
I like this direction I think we just need to organize all of the link pages now before can be merged into master. Unless we create a different branch to serve the live site & continue work in master
