### ISSUE TITLE
Mobile First Layout - Responsive Templates

### ISSUE THREAD

**Issue by rdev0rigin** [hurricane-response/florence_website#38]
I believe that the majority of the users would be using this site from a mobile device. Making sure that it's mobile friendly would be important. 

Mostly what Im notice is  the **content stacking** for small screens. Im not seeing much in the way of responsiveness. In my opinion, a single column layout is better for mobile. It helps people navigate content with small screens not having to worry about a horizontal scroll (aside from looking on maps).

**Comment by miklb** [comment]
I would have to understand more of what you are suggesting as I consider this layout mobile first to start with. The organization of the content I do agree could be better for mobile however I'm not sure we've fully fleshed out how the site will be utilized in the future.

**Comment by rdev0rigin** [comment]
Whoops! Your right it, most of it is. The only part I notice now is the pink banner. 

<img width="1440" alt="screen shot 2018-10-02 at 1 15 42 pm" src="https://user-images.githubusercontent.com/26286574/46374551-cc740a00-c645-11e8-9164-2fb34f2eef40.png">

**Comment by miklb** [comment]
Correct that is intentional to be a pinned notification

**Comment by rdev0rigin** [comment]
Im closing this issue, it turned out not to be one.
