### ISSUE TITLE
Better Evacuation Map

### ISSUE THREAD

**Issue by ChrisTheDBA** [hurricane-response/florence_website#9]
There are two resources for a better map from ESRI.

https://hifld-geoplatform.opendata.arcgis.com/datasets/hurricane-evacuation-routes

http://data.nconemap.com/geoportal/catalog/search/resource/details.page?uuid=%7B80E24A0D-69DF-42B9-B089-78A40F4CA696%7D

Either would be the basis for an map

**Comment by mikelmaron** [comment]
> https://hifld-geoplatform.opendata.arcgis.com/datasets/hurricane-evacuation-routes

this data could be downloaded and used to build an interactive mapbox map directly on the site. useful?

**Comment by miklb** [comment]
Get evac route from your location sure does

**Comment by skorasaurus** [comment]
Virginia's are at 
https://github.com/jonahadkins/vdem-evac-zones 

I'm not sure how these differ from above source.

**Comment by miklb** [comment]
I'm going to close this one and leave #1 open for future planning.
